"""add session io records

Revision ID: baa229ad49e8
Revises: a3f8c21d4e90
Create Date: 2026-08-03 16:50:57.634583
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "baa229ad49e8"
down_revision: str | None = "a3f8c21d4e90"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_input",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("idempotency_key", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("submit", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("settled_at", sa.String(), nullable=True),
        sa.Column("failure_reason", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", "idempotency_key"),
    )
    with op.batch_alter_table("session_input", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_session_input_task_id"), ["task_id"], unique=False)

    op.create_table(
        "session_transcript",
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("runner_id", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("columns", sa.Integer(), nullable=False),
        sa.Column("rows", sa.Integer(), nullable=False),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.Column("received_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
        ),
        sa.PrimaryKeyConstraint("task_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("session_transcript")
    with op.batch_alter_table("session_input", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_input_task_id"))

    op.drop_table("session_input")
    # ### end Alembic commands ###
