"""drop repo creds_volume

Revision ID: 9644848c9433
Revises: c2f1a8b4d3e7
Create Date: 2026-06-25 15:55:27.893739
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9644848c9433"
down_revision: str | None = "c2f1a8b4d3e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repo", schema=None) as batch_op:
        batch_op.drop_column("creds_volume")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repo", schema=None) as batch_op:
        batch_op.add_column(sa.Column("creds_volume", sa.String(), nullable=True))

    # ### end Alembic commands ###
