"""add created_at to task

Revision ID: faf3403c8b56
Revises: c5d5138649f4
Create Date: 2026-07-11 20:55:41.232553
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "faf3403c8b56"
down_revision: str | None = "c5d5138649f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.String(), nullable=True))

    # Backfill existing rows: use the oldest history entry's timestamp as the creation time.
    op.execute(
        "UPDATE task SET created_at = ("
        "  SELECT at FROM history"
        "  WHERE history.task_id = task.id"
        "  ORDER BY seq ASC LIMIT 1"
        ") WHERE created_at IS NULL"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
