#!/usr/bin/env python3
"""Extract one step's Action and Check blocks from the cutover runbook, verbatim.

The point is that the generated file contains the runbook's own bytes. No human
or model retypes anything, so a transcription slip is impossible by construction
— the only thing added is a wrapper that keeps a failure from closing an
interactive shell (the runbook's `set -Eeuo pipefail` is right for a script and
destroys EVIDENCE_DIR when sourced from a terminal).

    ./extract-cutover-step.py S04 > s04-cutover.sh
    source ./s04-cutover.sh
"""
import re
import sys
from pathlib import Path

RUNBOOK = Path(__file__).parent / "docs" / "runbooks" / "enforced-mode-cutover.md"


def blocks_for(step: str, text: str) -> tuple[str, str]:
    """Return (action, check) shell text for `step`, exactly as written.

    Steps are `## SNN — …` with `### Action` / `### Check`. Gates are
    `### GNN — …` with `#### Command` / `#### Check`, and they are NOT nested
    inside any step — S06 says to run G01–G07 "below", so extracting only the
    `## S` sections silently omits every gate. That omission made S06 report OK
    while none of the seven gates had run.
    """
    if step.startswith("G"):
        depth, first = "###", "Command"
    else:
        depth, first = "##", "Action"

    start = re.search(rf"^{depth} {re.escape(step)} — ", text, re.M)
    if not start:
        sys.exit(f"no such step: {step}")
    nxt = re.search(rf"^{depth} ", text[start.end():], re.M)
    section = text[start.start(): start.end() + (nxt.start() if nxt else len(text))]

    sub = "####" if step.startswith("G") else "###"

    def fenced(heading: str) -> str:
        m = re.search(rf"^{sub} {heading}\n\n```sh\n(.*?)^```", section, re.M | re.S)
        return m.group(1) if m else ""

    return fenced(first), fenced("Check")


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit("usage: extract-cutover-step.py <STEP>   e.g. S04")
    step = sys.argv[1]
    text = RUNBOOK.read_text()
    action, check = blocks_for(step, text)
    if not action:
        sys.exit(f"{step}: no Action block found")

    # `set -Eeuo pipefail` appears inside some Action blocks. Strip it: sourcing a
    # block that sets errexit kills the operator's shell on the first failure and
    # takes every export with it, including the mktemp EVIDENCE_DIR that later
    # steps depend on and that cannot be reconstructed.
    action = "\n".join(
        line for line in action.splitlines() if not re.match(r"^\s*set -[A-Za-z]*e", line)
    )

    # Each block runs inside a function with ERR_RETURN. That stops at the FIRST
    # failing command — checking only `$?` after the block would read the last
    # command's status and let a failed gate pass, which is the precise defect
    # this whole procedure exists to prevent. ERR_RETURN returns from the
    # function rather than exiting, so a failure costs the step, not the shell
    # and its unreconstructable EVIDENCE_DIR. Exports still propagate: S05, S07
    # and S08 assign inside their Check blocks, so a subshell would lose them.
    def wrap(name: str, body: str, label: str) -> list[str]:
        return [
            f"{name}() {{",
            "  setopt local_options err_return",
            body,
            "}",
            f"print '{step}: running {label}...'",
            f"{name}",
            f"_rc=$?; unset -f {name}",
            f"[ $_rc -eq 0 ] || {{ print -u2 '{step} {label.upper()} FAILED at exit '$_rc' — see the runbook Failure action for {step}'; return $_rc; }}",
            "",
        ]

    out = [
        f"# {step} — extracted verbatim from docs/runbooks/enforced-mode-cutover.md",
        "# Generated by extract-cutover-step.py. Do not hand-edit.",
        "# SOURCE this file; do not execute it. Later steps reuse its exports.",
        "",
    ]
    out += wrap("_cutover_action", action, "Action")
    if check:
        out += wrap("_cutover_check", check, "Check")
    out.append(f"print '{step} OK'")
    print("\n".join(out))


if __name__ == "__main__":
    main()
