# G01 — extracted verbatim from docs/runbooks/enforced-mode-cutover.md
# Generated by extract-cutover-step.py. Do not hand-edit.
# SOURCE this file; do not execute it. Later steps reuse its exports.

_cutover_action() {
  setopt local_options err_return
test "$(curl --silent --output /dev/null --write-out '%{http_code}' "$SERVICE_URL/healthz")" = 200
}
print 'G01: running Action...'
_cutover_action
_rc=$?; unset -f _cutover_action
[ $_rc -eq 0 ] || { print -u2 'G01 ACTION FAILED at exit '$_rc' — see the runbook Failure action for G01'; return $_rc; }

_cutover_check() {
  setopt local_options err_return
curl --silent --show-error --fail "$SERVICE_URL/healthz" | grep --fixed-strings '"status":"ok"'
printf 'G01: PASS\n' >> "$EVIDENCE_DIR/gates.txt"

}
print 'G01: running Check...'
_cutover_check
_rc=$?; unset -f _cutover_check
[ $_rc -eq 0 ] || { print -u2 'G01 CHECK FAILED at exit '$_rc' — see the runbook Failure action for G01'; return $_rc; }

print 'G01 OK'
