# G03 — extracted verbatim from docs/runbooks/enforced-mode-cutover.md
# Generated by extract-cutover-step.py. Do not hand-edit.
# SOURCE this file; do not execute it. Later steps reuse its exports.

_cutover_action() {
  setopt local_options err_return
curl --silent --show-error --fail --header "Authorization: Bearer $WRITE_TOKEN" "$SERVICE_URL/runners" --output "$EVIDENCE_DIR/G03-runners.json"
curl --silent --show-error --fail --header "Authorization: Bearer $WRITE_TOKEN" "$SERVICE_URL/runners/$NEW_RUNNER_ID" --output "$EVIDENCE_DIR/G03-runner.json"
}
print 'G03: running Action...'
_cutover_action
_rc=$?; unset -f _cutover_action
[ $_rc -eq 0 ] || { print -u2 'G03 ACTION FAILED at exit '$_rc' — see the runbook Failure action for G03'; return $_rc; }

_cutover_check() {
  setopt local_options err_return
kill -0 "$NEW_RUNNER_PID"
test "$(ps -o lstart= -p "$NEW_RUNNER_PID" | sed 's/^ *//')" = "$NEW_RUNNER_START"
uv --directory "$APP_ROOT" run python -m panopticon.core.cutover_runbook assert-runner-set "$EVIDENCE_DIR/G03-runners.json" "$NEW_RUNNER_ID"
uv --directory "$APP_ROOT" run python -m panopticon.core.cutover_runbook assert-runner-process "$NEW_RUNNER_PID" "$NEW_RUNNER_START" "$EVIDENCE_DIR/S04-runner-start-command.txt" "$PANOPTICON_CONFIG" "$AUTH_FILE_NAME" "$NEW_RUNNER_ID"
printf 'G03: PASS\n' >> "$EVIDENCE_DIR/gates.txt"

}
print 'G03: running Check...'
_cutover_check
_rc=$?; unset -f _cutover_check
[ $_rc -eq 0 ] || { print -u2 'G03 CHECK FAILED at exit '$_rc' — see the runbook Failure action for G03'; return $_rc; }

print 'G03 OK'
