# G04 — extracted verbatim from docs/runbooks/enforced-mode-cutover.md
# Generated by extract-cutover-step.py. Do not hand-edit.
# SOURCE this file; do not execute it. Later steps reuse its exports.

_cutover_action() {
  setopt local_options err_return
curl --silent --show-error --dump-header "$EVIDENCE_DIR/G04-headers.txt" --output "$EVIDENCE_DIR/G04-tasks.json" --write-out '%{http_code}' --header "Authorization: Bearer $READ_TOKEN" --header "Origin: $PWA_ORIGIN" "$SERVICE_URL/tasks" | tee "$EVIDENCE_DIR/G04-status.txt"
}
print 'G04: running Action...'
_cutover_action
_rc=$?; unset -f _cutover_action
[ $_rc -eq 0 ] || { print -u2 'G04 ACTION FAILED at exit '$_rc' — see the runbook Failure action for G04'; return $_rc; }

_cutover_check() {
  setopt local_options err_return
test "$(cat "$EVIDENCE_DIR/G04-status.txt")" != 401
test "$(cat "$EVIDENCE_DIR/G04-status.txt")" != 403
test "$(cat "$EVIDENCE_DIR/G04-status.txt")" = 200
grep --ignore-case --fixed-strings "access-control-allow-origin: $PWA_ORIGIN" "$EVIDENCE_DIR/G04-headers.txt"
printf 'G04: PASS\n' >> "$EVIDENCE_DIR/gates.txt"

}
print 'G04: running Check...'
_cutover_check
_rc=$?; unset -f _cutover_check
[ $_rc -eq 0 ] || { print -u2 'G04 CHECK FAILED at exit '$_rc' — see the runbook Failure action for G04'; return $_rc; }

print 'G04 OK'
