# G05 — extracted verbatim from docs/runbooks/enforced-mode-cutover.md
# Generated by extract-cutover-step.py. Do not hand-edit.
# SOURCE this file; do not execute it. Later steps reuse its exports.

_cutover_action() {
  setopt local_options err_return
test "$(curl --silent --output /dev/null --write-out '%{http_code}' --request PUT --header 'Content-Type: application/json' --header "Authorization: Bearer $READ_TOKEN" --data '{"turn":"agent"}' "$SERVICE_URL/tasks/$CANARY_TASK_ID/turn")" = 401
}
print 'G05: running Action...'
_cutover_action
_rc=$?; unset -f _cutover_action
[ $_rc -eq 0 ] || { print -u2 'G05 ACTION FAILED at exit '$_rc' — see the runbook Failure action for G05'; return $_rc; }

_cutover_check() {
  setopt local_options err_return
test -n "$CANARY_TASK_ID"
printf 'G05: PASS\n' >> "$EVIDENCE_DIR/gates.txt"

}
print 'G05: running Check...'
_cutover_check
_rc=$?; unset -f _cutover_check
[ $_rc -eq 0 ] || { print -u2 'G05 CHECK FAILED at exit '$_rc' — see the runbook Failure action for G05'; return $_rc; }

print 'G05 OK'
