# G06 — extracted verbatim from docs/runbooks/enforced-mode-cutover.md
# Generated by extract-cutover-step.py. Do not hand-edit.
# SOURCE this file; do not execute it. Later steps reuse its exports.

_cutover_action() {
  setopt local_options err_return
curl --silent --show-error --request OPTIONS --dump-header "$EVIDENCE_DIR/G06-preflight.txt" --output /dev/null --header "Origin: $PWA_ORIGIN" --header 'Access-Control-Request-Method: GET' --header 'Access-Control-Request-Headers: Authorization' "$SERVICE_URL/tasks"
curl --silent --show-error --dump-header "$EVIDENCE_DIR/G06-actual.txt" --output /dev/null --header "Authorization: Bearer $READ_TOKEN" --header "Origin: $PWA_ORIGIN" "$SERVICE_URL/tasks"
}
print 'G06: running Action...'
_cutover_action
_rc=$?; unset -f _cutover_action
[ $_rc -eq 0 ] || { print -u2 'G06 ACTION FAILED at exit '$_rc' — see the runbook Failure action for G06'; return $_rc; }

_cutover_check() {
  setopt local_options err_return
uv --directory "$APP_ROOT" run python - "$PWA_ORIGIN" "$EVIDENCE_DIR/G06-preflight.txt" "$EVIDENCE_DIR/G06-actual.txt" <<'PY'
import sys
origin = sys.argv[1]
for path in sys.argv[2:]:
    headers = {}
    for line in open(path):
        if ":" in line:
            name, value = line.split(":", 1)
            headers.setdefault(name.lower(), []).append(value.strip())
    assert headers.get("access-control-allow-origin") == [origin]
    assert "access-control-allow-credentials" not in headers
PY
printf 'G06: PASS\n' >> "$EVIDENCE_DIR/gates.txt"

}
print 'G06: running Check...'
_cutover_check
_rc=$?; unset -f _cutover_check
[ $_rc -eq 0 ] || { print -u2 'G06 CHECK FAILED at exit '$_rc' — see the runbook Failure action for G06'; return $_rc; }

print 'G06 OK'
