# G07 — extracted verbatim from docs/runbooks/enforced-mode-cutover.md
# Generated by extract-cutover-step.py. Do not hand-edit.
# SOURCE this file; do not execute it. Later steps reuse its exports.

_cutover_action() {
  setopt local_options err_return
printf 'On the installed phone board at %s, open the fleet and enter the exact displayed task name: ' "$PHONE_BOARD_URL"
read -r OBSERVED_PHONE_TASK
printf '%s\n' "$OBSERVED_PHONE_TASK" > "$EVIDENCE_DIR/G07-phone-observation.txt"
curl --silent --show-error --fail --header "Authorization: Bearer $READ_TOKEN" "$SERVICE_URL/tasks" --output "$EVIDENCE_DIR/G07-api.json"
}
print 'G07: running Action...'
_cutover_action
_rc=$?; unset -f _cutover_action
[ $_rc -eq 0 ] || { print -u2 'G07 ACTION FAILED at exit '$_rc' — see the runbook Failure action for G07'; return $_rc; }

_cutover_check() {
  setopt local_options err_return
uv --directory "$APP_ROOT" run python - "$KNOWN_TASK_NAME" "$EVIDENCE_DIR/G07-phone-observation.txt" "$EVIDENCE_DIR/G07-api.json" <<'PY'
import json, sys
name, phone_path, api_path = sys.argv[1:]
tasks = json.load(open(api_path))
assert open(phone_path).read().strip() == name
assert any(name in {task.get("name"), task.get("slug")} for task in tasks)
PY
printf 'G07: PASS\n' >> "$EVIDENCE_DIR/gates.txt"

}
print 'G07: running Check...'
_cutover_check
_rc=$?; unset -f _cutover_check
[ $_rc -eq 0 ] || { print -u2 'G07 CHECK FAILED at exit '$_rc' — see the runbook Failure action for G07'; return $_rc; }

print 'G07 OK'
