# S03 — extracted verbatim from docs/runbooks/enforced-mode-cutover.md
# Generated by extract-cutover-step.py. Do not hand-edit.
# SOURCE this file; do not execute it. Later steps reuse its exports.

_cutover_action() {
  setopt local_options err_return
test -z "$TASK_CONTAINERS" || printf '%s\n' "$TASK_CONTAINERS" | xargs docker stop
}
print 'S03: running Action...'
_cutover_action
_rc=$?; unset -f _cutover_action
[ $_rc -eq 0 ] || { print -u2 'S03 ACTION FAILED at exit '$_rc' — see the runbook Failure action for S03'; return $_rc; }

_cutover_check() {
  setopt local_options err_return
docker ps --quiet --filter label=panopticon.task | tee "$EVIDENCE_DIR/S03-running-after.txt"
test ! -s "$EVIDENCE_DIR/S03-running-after.txt"
docker ps --all --quiet --no-trunc --filter label=panopticon.task | tee "$EVIDENCE_DIR/S03-all-container-ids-before-enforcement.txt"

}
print 'S03: running Check...'
_cutover_check
_rc=$?; unset -f _cutover_check
[ $_rc -eq 0 ] || { print -u2 'S03 CHECK FAILED at exit '$_rc' — see the runbook Failure action for S03'; return $_rc; }

print 'S03 OK'
