# S04 — extracted verbatim from docs/runbooks/enforced-mode-cutover.md
# Generated by extract-cutover-step.py. Do not hand-edit.
# SOURCE this file; do not execute it. Later steps reuse its exports.

_cutover_action() {
  setopt local_options err_return
tmux -L panopticon new-session -d -s runner -c "$APP_ROOT" "exec env PANOPTICON_CONFIG='$PANOPTICON_CONFIG' PANOPTICON_SERVICE_AUTH_FILE='$AUTH_FILE_NAME' PANOPTICON_SERVICE_AUTH_MODE=enforced PANOPTICON_RUNNER_ID='$NEW_RUNNER_ID' uv run python -m panopticon.sessionservice.host"
tmux -L panopticon set-environment -g PANOPTICON_SERVICE_AUTH_FILE "$AUTH_FILE_NAME"
tmux -L panopticon set-environment -g PANOPTICON_SERVICE_AUTH_MODE enforced
tmux -L panopticon set-environment -g PANOPTICON_CONFIG "$PANOPTICON_CONFIG"
tmux -L panopticon set-environment -g PANOPTICON_BROWSER_ORIGINS "$PWA_ORIGIN"
tmux -L panopticon new-session -d -s dashboard -c "$APP_ROOT" "until curl --silent --fail '$SERVICE_URL/healthz' >/dev/null; do sleep 1; done; exec env PANOPTICON_CONFIG='$PANOPTICON_CONFIG' PANOPTICON_SERVICE_AUTH_FILE='$AUTH_FILE_NAME' PANOPTICON_SERVICE_AUTH_MODE=enforced PANOPTICON_BROWSER_ORIGINS='$PWA_ORIGIN' uv run panopticon --service-url '$SERVICE_URL' dashboard"
export NEW_RUNNER_PID="$(tmux -L panopticon display-message -p -t runner '#{pane_pid}')"
export NEW_DASHBOARD_PID="$(tmux -L panopticon display-message -p -t dashboard '#{pane_pid}')"
export NEW_RUNNER_START="$(ps -o lstart= -p "$NEW_RUNNER_PID" | sed 's/^ *//')"
export NEW_DASHBOARD_START="$(ps -o lstart= -p "$NEW_DASHBOARD_PID" | sed 's/^ *//')"
ps -o pid= -o lstart= -p "$NEW_RUNNER_PID,$NEW_DASHBOARD_PID" | tee "$EVIDENCE_DIR/S04-client-identities-after.txt"
tmux -L panopticon display-message -p -t runner '#{pane_start_command}' | sed 's/^"//; s/"$//' | tee "$EVIDENCE_DIR/S04-runner-start-command.txt"
tmux -L panopticon display-message -p -t dashboard '#{pane_start_command}' | sed 's/^"//; s/"$//' | tee "$EVIDENCE_DIR/S04-dashboard-start-command.txt"
}
print 'S04: running Action...'
_cutover_action
_rc=$?; unset -f _cutover_action
[ $_rc -eq 0 ] || { print -u2 'S04 ACTION FAILED at exit '$_rc' — see the runbook Failure action for S04'; return $_rc; }

_cutover_check() {
  setopt local_options err_return
test "$NEW_RUNNER_PID" != "$OLD_RUNNER_PID"
test "$NEW_DASHBOARD_PID" != "$OLD_DASHBOARD_PID"
! cmp --silent "$EVIDENCE_DIR/S01-client-identities-before.txt" "$EVIDENCE_DIR/S04-client-identities-after.txt"
test -n "$NEW_RUNNER_START"
test -n "$NEW_DASHBOARD_START"
kill -0 "$NEW_RUNNER_PID"
kill -0 "$NEW_DASHBOARD_PID"
grep --fixed-strings "PANOPTICON_RUNNER_ID='$NEW_RUNNER_ID'" "$EVIDENCE_DIR/S04-runner-start-command.txt"
grep --fixed-strings "exec env" "$EVIDENCE_DIR/S04-runner-start-command.txt"
uv --directory "$APP_ROOT" run python -m panopticon.core.cutover_runbook assert-dashboard-process "$NEW_DASHBOARD_PID" "$NEW_DASHBOARD_START" "$EVIDENCE_DIR/S04-dashboard-start-command.txt" "$PANOPTICON_CONFIG" "$AUTH_FILE_NAME" "$PWA_ORIGIN" "$SERVICE_URL"
test "$(ps -o lstart= -p "$NEW_RUNNER_PID" | sed 's/^ *//')" = "$NEW_RUNNER_START"
test "$(ps -o lstart= -p "$NEW_DASHBOARD_PID" | sed 's/^ *//')" = "$NEW_DASHBOARD_START"
! kill -0 "$OLD_RUNNER_PID" 2>/dev/null || test "$(ps -o lstart= -p "$OLD_RUNNER_PID" | sed 's/^ *//')" != "$OLD_RUNNER_START"
! kill -0 "$OLD_DASHBOARD_PID" 2>/dev/null || test "$(ps -o lstart= -p "$OLD_DASHBOARD_PID" | sed 's/^ *//')" != "$OLD_DASHBOARD_START"
uv --directory "$APP_ROOT" run python -m panopticon.core.cutover_runbook assert-process-replaced "$OLD_RUNNER_PID" "$OLD_RUNNER_START"
uv --directory "$APP_ROOT" run python -m panopticon.core.cutover_runbook assert-process-replaced "$OLD_DASHBOARD_PID" "$OLD_DASHBOARD_START"
test -s "$EVIDENCE_DIR/S01-client-identities-before.txt"
test -s "$EVIDENCE_DIR/S04-client-identities-after.txt"
test -n "$OLD_RUNNER_START"
test -n "$OLD_DASHBOARD_START"
printf 'G10: PASS\n' >> "$EVIDENCE_DIR/gates.txt"
printf 'G11: PASS\n' >> "$EVIDENCE_DIR/gates.txt"
docker ps --quiet --filter label=panopticon.task | tee "$EVIDENCE_DIR/G08-running.txt"
test ! -s "$EVIDENCE_DIR/G08-running.txt"
printf 'G08: PASS\n' >> "$EVIDENCE_DIR/gates.txt"

}
print 'S04: running Check...'
_cutover_check
_rc=$?; unset -f _cutover_check
[ $_rc -eq 0 ] || { print -u2 'S04 CHECK FAILED at exit '$_rc' — see the runbook Failure action for S04'; return $_rc; }

print 'S04 OK'
