# S05 — extracted verbatim from docs/runbooks/enforced-mode-cutover.md
# Generated by extract-cutover-step.py. Do not hand-edit.
# SOURCE this file; do not execute it. Later steps reuse its exports.

_cutover_action() {
  setopt local_options err_return
export PANOPTICON_SERVICE_AUTH_MODE=enforced
export PANOPTICON_SERVICE_AUTH_FILE="$AUTH_FILE_NAME"
export PANOPTICON_BROWSER_ORIGINS="$PWA_ORIGIN"
export ENFORCEMENT_STARTED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
printf '%s\n' "$ENFORCEMENT_STARTED_AT" > "$EVIDENCE_DIR/S05-enforcement-started-at.txt"
tmux -L panopticon new-session -d -s service -c "$APP_ROOT" "exec env PANOPTICON_CONFIG='$PANOPTICON_CONFIG' PANOPTICON_SERVICE_AUTH_MODE='$PANOPTICON_SERVICE_AUTH_MODE' PANOPTICON_SERVICE_AUTH_FILE='$PANOPTICON_SERVICE_AUTH_FILE' PANOPTICON_BROWSER_ORIGINS='$PANOPTICON_BROWSER_ORIGINS' uv run python -m panopticon.taskservice"
}
print 'S05: running Action...'
_cutover_action
_rc=$?; unset -f _cutover_action
[ $_rc -eq 0 ] || { print -u2 'S05 ACTION FAILED at exit '$_rc' — see the runbook Failure action for S05'; return $_rc; }

_cutover_check() {
  setopt local_options err_return
export SERVICE_DEADLINE="$(( $(date +%s) + 300 ))"
until curl --silent --show-error --fail "$SERVICE_URL/healthz"; do
  test "$(date +%s)" -lt "$SERVICE_DEADLINE"
  sleep 1
done
tmux -L panopticon show-environment -g PANOPTICON_BROWSER_ORIGINS | grep --fixed-strings "PANOPTICON_BROWSER_ORIGINS=$PWA_ORIGIN"

}
print 'S05: running Check...'
_cutover_check
_rc=$?; unset -f _cutover_check
[ $_rc -eq 0 ] || { print -u2 'S05 CHECK FAILED at exit '$_rc' — see the runbook Failure action for S05'; return $_rc; }

print 'S05 OK'
