# S06 — extracted verbatim from docs/runbooks/enforced-mode-cutover.md
# Generated by extract-cutover-step.py. Do not hand-edit.
# SOURCE this file; do not execute it. Later steps reuse its exports.

_cutover_action() {
  setopt local_options err_return
export WRITE_TOKEN="$(uv --directory "$APP_ROOT" run python -c 'from panopticon.taskservice.auth import environment_token; print(environment_token())')"
export READ_TOKEN="$(uv --directory "$APP_ROOT" run python -c 'from panopticon.taskservice.auth import environment_token; print(environment_token(privilege="read"))')"
}
print 'S06: running Action...'
_cutover_action
_rc=$?; unset -f _cutover_action
[ $_rc -eq 0 ] || { print -u2 'S06 ACTION FAILED at exit '$_rc' — see the runbook Failure action for S06'; return $_rc; }

_cutover_check() {
  setopt local_options err_return
test -n "$WRITE_TOKEN"
test -n "$READ_TOKEN"

}
print 'S06: running Check...'
_cutover_check
_rc=$?; unset -f _cutover_check
[ $_rc -eq 0 ] || { print -u2 'S06 CHECK FAILED at exit '$_rc' — see the runbook Failure action for S06'; return $_rc; }

print 'S06 OK'
