# S08 — extracted verbatim from docs/runbooks/enforced-mode-cutover.md
# Generated by extract-cutover-step.py. Do not hand-edit.
# SOURCE this file; do not execute it. Later steps reuse its exports.

_cutover_action() {
  setopt local_options err_return
curl --silent --show-error --fail --request POST --header "Authorization: Bearer $WRITE_TOKEN" "$SERVICE_URL/runners/$OLD_RUNNER_ID/reclaim" --output "$EVIDENCE_DIR/S08-reclaimed.json"
}
print 'S08: running Action...'
_cutover_action
_rc=$?; unset -f _cutover_action
[ $_rc -eq 0 ] || { print -u2 'S08 ACTION FAILED at exit '$_rc' — see the runbook Failure action for S08'; return $_rc; }

_cutover_check() {
  setopt local_options err_return
export FLEET_DEADLINE="$(( $(date +%s) + 1800 ))"
until curl --silent --show-error --fail --header "Authorization: Bearer $WRITE_TOKEN" "$SERVICE_URL/tasks" --output "$EVIDENCE_DIR/S08-tasks.json" && uv --directory "$APP_ROOT" run python - "$EVIDENCE_DIR/S08-tasks.json" <<'PY'
import json, sys
tasks = json.load(open(sys.argv[1]))
assert all(
    task["terminal"]
    or task["container_status"] == "live"
    or task["container_status"] == "gated"
    or (task["container_status"] == "failed" and task["lifecycle_detail"])
    for task in tasks
)
PY
do
  test "$(date +%s)" -lt "$FLEET_DEADLINE"
  sleep 5
done
uv --directory "$APP_ROOT" run python - "$EVIDENCE_DIR/S08-tasks.json" > "$EVIDENCE_DIR/S08-resumed-harnesses.txt" <<'PY'
import json, sys
tasks = json.load(open(sys.argv[1]))
print("\n".join(sorted({task["harness"] for task in tasks if task["container_status"] == "live"})))
PY
: > "$EVIDENCE_DIR/S08-resume-observations.txt"
for harness in $(cat "$EVIDENCE_DIR/S08-resumed-harnesses.txt"); do
  printf 'Attach to one respawned %s task, verify pre-cutover history is visible and a new turn continues it, then enter confirmed: ' "$harness"
  read -r resumed
  test "$resumed" = confirmed
  printf '%s: transcript-visible-and-continuation-confirmed\n' "$harness" >> "$EVIDENCE_DIR/S08-resume-observations.txt"
done

}
print 'S08: running Check...'
_cutover_check
_rc=$?; unset -f _cutover_check
[ $_rc -eq 0 ] || { print -u2 'S08 CHECK FAILED at exit '$_rc' — see the runbook Failure action for S08'; return $_rc; }

print 'S08 OK'
