# S09 — extracted verbatim from docs/runbooks/enforced-mode-cutover.md
# Generated by extract-cutover-step.py. Do not hand-edit.
# SOURCE this file; do not execute it. Later steps reuse its exports.

_cutover_action() {
  setopt local_options err_return
{
  printf 'Enforced-mode cutover evidence for %s\n\n' "$DEPLOY_REV"
  cat "$EVIDENCE_DIR/gates.txt"
  printf '\nNew follow-up work (append to issue #203; do not duplicate #202/#203):\n'
  cat "$EVIDENCE_DIR/followups.md"
  printf '\nEvidence files:\n'
  find "$EVIDENCE_DIR" -maxdepth 1 -type f -exec basename {} \; | sort
} > "$EVIDENCE_DIR/cutover-summary.md"
gh issue comment 203 --repo tylerwillis/panopticon --body-file "$EVIDENCE_DIR/cutover-summary.md"
}
print 'S09: running Action...'
_cutover_action
_rc=$?; unset -f _cutover_action
[ $_rc -eq 0 ] || { print -u2 'S09 ACTION FAILED at exit '$_rc' — see the runbook Failure action for S09'; return $_rc; }

_cutover_check() {
  setopt local_options err_return
uv --directory "$APP_ROOT" run python - "$EVIDENCE_DIR/gates.txt" <<'PY'
import sys
lines = open(sys.argv[1]).read().splitlines()
expected = ["G10: PASS", "G11: PASS", "G08: PASS"]
expected.extend(f"G{number:02d}: PASS" for number in range(1, 8))
expected.append("G09: PASS")
assert lines == expected
PY
gh issue view 203 --repo tylerwillis/panopticon --comments --json comments --jq '.comments[-1].body' | grep --fixed-strings 'G11: PASS'

}
print 'S09: running Check...'
_cutover_check
_rc=$?; unset -f _cutover_check
[ $_rc -eq 0 ] || { print -u2 'S09 CHECK FAILED at exit '$_rc' — see the runbook Failure action for S09'; return $_rc; }

print 'S09 OK'
