"""add hook_file to repo

Revision ID: 5066c0371860
Revises: 9644848c9433
Create Date: 2026-06-25 22:23:22.722787
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5066c0371860'
down_revision: str | None = 'ed8efc0b01ac'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hook_file', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repo', schema=None) as batch_op:
        batch_op.drop_column('hook_file')

    # ### end Alembic commands ###
