"""add repo workflow preferences

Revision ID: 596be4c1bf2a
Revises: 23b38893ccf9
Create Date: 2026-06-30 15:59:40.078800
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '596be4c1bf2a'
down_revision: str | None = '23b38893ccf9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled_workflows', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('disabled_workflows', sa.JSON(), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repo', schema=None) as batch_op:
        batch_op.drop_column('disabled_workflows')
        batch_op.drop_column('enabled_workflows')

    # ### end Alembic commands ###
